" plugin loading with pathogen
execute pathogen#infect()

""" colurs
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red

""""""" defaults
"" colours
syntax on
set t_Co=256
set background=light

set nocompatible
set backspace=2
set showmode
set nrformats-=octal
filetype plugin indent on
set nofoldenable
" slow as shit highlighting on new
set regexpengine=1
set mouse=v
set ttymouse=xterm2

""""""" binds
let mapleader = "\<Space>"


" git commit
map <F9> :Gwrite<CR>:let @" =expand('%:t')<CR>:Gcommit<CR>pA:<Space>

" pasting
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
map <F1> :set nu!<CR>:set relativenumber!<CR>

" whitespace
map <F7> mzgg=G`z<CR>
map <F8> :StripWhitespace<CR>
map <F12> :set spell!<CR>
inoremap <S-Tab> <C-V><Tab>

""""""" movement
" make navigating splits easier
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h
" make navigating tabs easier
map <Leader>l <esc>:tabprevious<CR>
map <Leader>h <esc>:tabnext<CR>
" map sort function to a key
vnoremap <Leader>s :sort<CR>

""""""" dirs
set directory=~/.vim/.swap//
set backupdir=~/.vim/.tmp//
set undodir=~/.vim/.undo//

""""""" tabs and indents
set expandtab
set tabstop=4
set shiftwidth=4
" easier code indenting
vnoremap < <gv
vnoremap > >gv
" tabs and indents per file type
autocmd Filetype sls setlocal ts=2 sts=2 sw=2
autocmd Filetype bash setlocal ts=2 sts=2 sw=2
autocmd Filetype yaml setlocal ts=2 sts=2 sw=2
autocmd Filetype yml setlocal ts=2 sts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype Dockerfile setlocal ts=4 sts=4 sw=4
autocmd Filetype jinja syntax on

" Showing line numbers and length
set colorcolumn=80
highlight ColorColumn ctermbg=233

" airline
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
set laststatus=2
let g:airline_powerline_fonts = 1

" generate 128char string
nnoremap <F6> :r! pwgen 128 -s -1<CR>kJ

" generate sshkeypair for salt pillar
nnoremap <F5> :r! ssh-keygen -t rsa -f /tmp/vimkey -N '' >/dev/null<Enter>i<Tab>ssh_rsa_priv:<Space>\|<CR><ESC>:r /tmp/vimkey<CR>kdd<C-v>GI<Tab><Tab><ESC>Go<Tab>ssh_key_pub:<Space>\|<CR><ESC>:r /tmp/vimkey.pub<CR>kddi<Tab><Tab><ESC>:r! rm -rf /tmp/vimkey*<CR>
