#!/usr/bin/env bash

hostname=$(hostname -s)

is_connected() {
    if xrandr | grep "$1" | grep -q " connected"; then
        return 0
    else
        return 1
    fi
}

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if [[ "${hostname}" == "ryanlaptop" ]]; then
    laptop="eDP-1"
    dell_left="DP-1-1"
    dell_right="DP-1-3"

    # If externals plugged in
    if is_connected ${dell_left} && is_connected ${dell_right}; then
        MONITOR="${laptop}" polybar side &
        MONITOR="${dell_right}" polybar side &
        MONITOR="${dell_left}" polybar main -l info&
    else # Just laptop
        MONITOR="${laptop}" polybar main &
    fi
fi

if [[ "${hostname}" == "tfu" ]]; then
    dell_right="DP-1-1"
    dell_left="DP-1-2"
    predator="DP-2-2"
    laptop="eDP-1"

    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    # If externals plugged in
    if is_connected ${predator} && is_connected ${dell_left} && is_connected ${dell_right}; then
        MONITOR="${predator}" polybar main &
        MONITOR="${dell_right}" polybar side &
        MONITOR="${dell_left}" polybar side &
    else # Just laptop
        MONITOR="${laptop}" polybar laptop &
    fi
fi

if [[ "${hostname}" == "warbastard" ]]; then
    right="DVI-D-0"
    middle="DP-0"
    left="DP-2"

    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    MONITOR="${right}" polybar side &
    MONITOR="${middle}" polybar main &
    MONITOR="${left}" polybar side &
fi
