#!/usr/bin/env bash

hostname=$(hostname -s)

is_connected() {
    if xrandr | grep "$1" | grep -q " connected"; then
        return 0
    else
        return 1
    fi
}


if [[ "${hostname}" == "tfu" ]]; then
    dell_right="DP-1-1"
    dell_left="DP-1-2"
    predator="DP-2-2"
    laptop="eDP-1"

    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    # If externals plugged in
    if is_connected ${predator} && is_connected ${dell_left} && is_connected ${dell_right}; then
        polybar predator &
        polybar dell_left &
        polybar dell_right &
    else # Just laptop
        polybar laptop &
    fi
fi
