# Disable terminal flow control (^s & ^q)
stty -ixon
stty -ixoff

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
HISTSIZE=50000
HISTFILESIZE=500000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Load envars
if [ -f ~/.bash_envars ]; then
    . ~/.config/dotfiles/bash_envars
fi

# Load secret envars (not uploaded to git....)
if [ -f ~/.bash_secrets ]; then
    . ~/.config/dotfiles/bash_secrets
fi


# Load colours
if [ -f ~/.bash_colours ]; then
    . ~/.config/dotfiles/bash_colours
fi

# Load aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.config/dotfiles/bash_aliases
fi

# Load prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.config/dotfiles/bash_prompt
else
    function _build_prompt {
      PS1="\u@\h:\w\$ "
      return 0
    }
    PROMPT_COMMAND="_build_prompt; $PROMPT_COMMAND"
fi

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# disable caps lock
setxkbmap -option caps:none
