# Disable terminal flow control (^s & ^q)
stty -ixon
stty -ixoff

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# append to the history file, don't overwrite it
# make it large
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=50000
HISTFILESIZE=500000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Load subfiles, always load secrets first, envars used in other files
dotfiles=(
    ~/.bash_secrets
    ~/.bash_work
    ~/.config/dotfiles/bash/aliases
    ~/.config/dotfiles/bash/envars
    ~/.config/dotfiles/bash/logout
    ~/.config/dotfiles/bash/profile
    ~/.config/dotfiles/bash/ssh
    ~/.config/dotfiles/bash/aws
)

for file in "${dotfiles[@]}"; do
    if [[ -f "${file}" ]]; then
        . "${file}"
    fi
done

# Load prompt seperately so we don't end up without a PS1
if [ -f ~/.config/dotfiles/bash/prompt ]; then
    source ~/.config/dotfiles/bash/prompt
else
    function _build_prompt {
      PS1="\u@\h:\w\$ "
      return 0
    }
    PROMPT_COMMAND="_build_prompt; $PROMPT_COMMAND"
fi

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
  fi
fi

# disable caps lock
setxkbmap -option caps:none

complete -C /home/ryan/bin/terraform terraform
