#!/usr/bin/env/bash

if [[ $(hostname) == 'ryanlaptop' ]]; then
  agent_started=0
  export GPG_TTY="$(tty)"
  export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
  gpg-connect-agent updatestartuptty /bye
  agent_started=1
else
  agent_started=0
  if ! env | grep -q SSH_AGENT_PID >/dev/null; then
    echo "Starting ssh agent"
    eval $(ssh-agent -s)
  fi
  agent_started=1
fi
